# Generated by Django 4.1.7 on 2023-02-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('title',)},
        ),
    ]
